# Generated by Django 3.2.1 on 2021-05-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GermanDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True)),
                ('sex', models.CharField(blank=True, choices=[(1, 'Female')], max_length=10)),
                ('job', models.CharField(max_length=100)),
                ('housing', models.CharField(max_length=50)),
                ('credit_amount', models.FloatField(blank=True, max_length=50)),
                ('duration', models.IntegerField(blank=True)),
                ('purpose', models.CharField(blank=True, max_length=50)),
                ('risk', models.CharField(blank=True, choices=[(1, 'Bad')], max_length=10)),
            ],
        ),
    ]
