# Generated by Django 3.2.1 on 2021-05-29 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='germandatamodel',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='germandatamodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='germandatamodel',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='germandatamodel',
            name='credit_amount',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='germandatamodel',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
