# Generated by Django 3.2.1 on 2021-06-23 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210623_0618'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='PredictionRequest',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
