/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
/*
 * Fineract Credit Scorecard
 * An API module for credit risk assessment
 *
 * The version of the OpenAPI document: 0.1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.apache.fineract.credit.scorecard.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PredictionResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class PredictionResponse {
  public static final String SERIALIZED_NAME_PROBABILITY = "probability";
  @SerializedName(SERIALIZED_NAME_PROBABILITY)
  private Float probability;

  public static final String SERIALIZED_NAME_LABEL = "label";
  @SerializedName(SERIALIZED_NAME_LABEL)
  private String label;

  public static final String SERIALIZED_NAME_METHOD = "method";
  @SerializedName(SERIALIZED_NAME_METHOD)
  private String method;

  public static final String SERIALIZED_NAME_COLOR = "color";
  @SerializedName(SERIALIZED_NAME_COLOR)
  private String color;

  public static final String SERIALIZED_NAME_WILKIS_LAMBDA = "wilkis_lambda";
  @SerializedName(SERIALIZED_NAME_WILKIS_LAMBDA)
  private Float wilkisLambda;

  public static final String SERIALIZED_NAME_PILLAIS_TRACE = "pillais_trace";
  @SerializedName(SERIALIZED_NAME_PILLAIS_TRACE)
  private Float pillaisTrace;

  public static final String SERIALIZED_NAME_HOTELLING_TAWLEY = "hotelling_tawley";
  @SerializedName(SERIALIZED_NAME_HOTELLING_TAWLEY)
  private Float hotellingTawley;

  public static final String SERIALIZED_NAME_ROYS_REATEST_ROOTS = "roys_reatest_roots";
  @SerializedName(SERIALIZED_NAME_ROYS_REATEST_ROOTS)
  private Float roysReatestRoots;

  public static final String SERIALIZED_NAME_REQUEST_ID = "request_id";
  @SerializedName(SERIALIZED_NAME_REQUEST_ID)
  private Integer requestId;


  public PredictionResponse probability(Float probability) {
    
    this.probability = probability;
    return this;
  }

   /**
   * Get probability
   * @return probability
  **/
  @ApiModelProperty(required = true, value = "")

  public Float getProbability() {
    return probability;
  }


  public void setProbability(Float probability) {
    this.probability = probability;
  }


  public PredictionResponse label(String label) {
    
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @ApiModelProperty(required = true, value = "")

  public String getLabel() {
    return label;
  }


  public void setLabel(String label) {
    this.label = label;
  }


  public PredictionResponse method(String method) {
    
    this.method = method;
    return this;
  }

   /**
   * Get method
   * @return method
  **/
  @ApiModelProperty(required = true, value = "")

  public String getMethod() {
    return method;
  }


  public void setMethod(String method) {
    this.method = method;
  }


  public PredictionResponse color(String color) {
    
    this.color = color;
    return this;
  }

   /**
   * Get color
   * @return color
  **/
  @ApiModelProperty(required = true, value = "")

  public String getColor() {
    return color;
  }


  public void setColor(String color) {
    this.color = color;
  }


  public PredictionResponse wilkisLambda(Float wilkisLambda) {
    
    this.wilkisLambda = wilkisLambda;
    return this;
  }

   /**
   * Get wilkisLambda
   * @return wilkisLambda
  **/
  @ApiModelProperty(required = true, value = "")

  public Float getWilkisLambda() {
    return wilkisLambda;
  }


  public void setWilkisLambda(Float wilkisLambda) {
    this.wilkisLambda = wilkisLambda;
  }


  public PredictionResponse pillaisTrace(Float pillaisTrace) {
    
    this.pillaisTrace = pillaisTrace;
    return this;
  }

   /**
   * Get pillaisTrace
   * @return pillaisTrace
  **/
  @ApiModelProperty(required = true, value = "")

  public Float getPillaisTrace() {
    return pillaisTrace;
  }


  public void setPillaisTrace(Float pillaisTrace) {
    this.pillaisTrace = pillaisTrace;
  }


  public PredictionResponse hotellingTawley(Float hotellingTawley) {
    
    this.hotellingTawley = hotellingTawley;
    return this;
  }

   /**
   * Get hotellingTawley
   * @return hotellingTawley
  **/
  @ApiModelProperty(required = true, value = "")

  public Float getHotellingTawley() {
    return hotellingTawley;
  }


  public void setHotellingTawley(Float hotellingTawley) {
    this.hotellingTawley = hotellingTawley;
  }


  public PredictionResponse roysReatestRoots(Float roysReatestRoots) {
    
    this.roysReatestRoots = roysReatestRoots;
    return this;
  }

   /**
   * Get roysReatestRoots
   * @return roysReatestRoots
  **/
  @ApiModelProperty(required = true, value = "")

  public Float getRoysReatestRoots() {
    return roysReatestRoots;
  }


  public void setRoysReatestRoots(Float roysReatestRoots) {
    this.roysReatestRoots = roysReatestRoots;
  }


  public PredictionResponse requestId(Integer requestId) {
    
    this.requestId = requestId;
    return this;
  }

   /**
   * Get requestId
   * @return requestId
  **/
  @ApiModelProperty(required = true, value = "")

  public Integer getRequestId() {
    return requestId;
  }


  public void setRequestId(Integer requestId) {
    this.requestId = requestId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PredictionResponse predictionResponse = (PredictionResponse) o;
    return Objects.equals(this.probability, predictionResponse.probability) &&
        Objects.equals(this.label, predictionResponse.label) &&
        Objects.equals(this.method, predictionResponse.method) &&
        Objects.equals(this.color, predictionResponse.color) &&
        Objects.equals(this.wilkisLambda, predictionResponse.wilkisLambda) &&
        Objects.equals(this.pillaisTrace, predictionResponse.pillaisTrace) &&
        Objects.equals(this.hotellingTawley, predictionResponse.hotellingTawley) &&
        Objects.equals(this.roysReatestRoots, predictionResponse.roysReatestRoots) &&
        Objects.equals(this.requestId, predictionResponse.requestId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(probability, label, method, color, wilkisLambda, pillaisTrace, hotellingTawley, roysReatestRoots, requestId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PredictionResponse {\n");
    sb.append("    probability: ").append(toIndentedString(probability)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    wilkisLambda: ").append(toIndentedString(wilkisLambda)).append("\n");
    sb.append("    pillaisTrace: ").append(toIndentedString(pillaisTrace)).append("\n");
    sb.append("    hotellingTawley: ").append(toIndentedString(hotellingTawley)).append("\n");
    sb.append("    roysReatestRoots: ").append(toIndentedString(roysReatestRoots)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

